<?php

namespace AppBundle\Repository;

/**
* TriageRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class TriageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMostRecentErrataDate($count = 1)
    {
        $em = $this->getDoctrine()->getManager();
        $query = $em->createQuery(
            'SELECT t
            FROM AppBundle:Triage t
            ORDER BY p.erratadate DESC
            LIMIT :count'
        )
        ->setParameter('count', $count);

        $res = $query->getResult();

        return $res;
    }

    public function findMostRecentErrataModified($count = 1)
    {
        $em = $this->getDoctrine()->getManager();
        $query = $em->createQuery(
            'SELECT t
            FROM AppBundle:Triage t
            ORDER BY p.lastchange DESC
            LIMIT :count'
        )
        ->setParameter('count', $count);

        $res = $query->getResult();

        return $res;
    }
}
