<?php

namespace AppBundle\Repository\;

/**
 * TriageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TriageRepository extends \Doctrine\ORM\EntityRepository
{
}
