<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Triage;

/**
* TriageRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class TriageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMostRecentErrataDate($count = 1)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT t
            FROM AppBundle:Triage t
            ORDER BY p.erratadate DESC
            LIMIT :count'
        )
        ->setParameter('count', $count);

        $res = $query->getResult();

        return $res;
    }

    public function findMostRecentErrataModified($count = 1)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT t
            FROM AppBundle:Triage t
            ORDER BY p.lastchange DESC
            LIMIT :count'
        )
        ->setParameter('count', $count);

        $res = $query->getResult();

        return $res;
    }

    public function findById($id)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT t
            FROM AppBundle:Triage t
            WHERE t.id = :id'
        )
        ->setParameter('id', $id);

        // $res = $query->getResult();

        // return $res;
        return $query->setMaxResults(1)->getOneOrNullResult();
    }

    public function findByErrata($errata)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT t
            FROM AppBundle:Triage t
            WHERE t.errata = :errata'
        )
        ->setParameter('errata', $errata);

        // $res = $query->getResult();

        // return $res;
        
        return $query->setMaxResults(1)->getOneOrNullResult();
    }

    public function findAll($limit = 0, $offset = 0, $orderBy = array())
    {
        //return $this->db->fetchAll("SELECT * FROM TeleinfoHpHc WHERE ");
        // Provide a default orderBy.
        if (!$orderBy) {
            $orderBy = array('timestamp' => 'ASC');
        }

        $qb = $this->db->createQueryBuilder();
        $qb
        ->select('e.*')
        ->from('TeleinfoHpHc', 'e')
        ->setFirstResult($offset)
        ->orderBy('e.' . key($orderBy), current($orderBy));

        if ($limit != 0) {
            $qb->setMaxResults($limit);
        }

        $statement = $qb->execute();

        return $statement->fetchAll();
    }

    public function save(Triage $triage)
    {
        $em = $this->getEntityManager();

        // tells Doctrine you want to (eventually) save the Triage (no queries yet)
        $em->persist($triage);

        // actually executes the queries (i.e. the INSERT query)
        $em->flush();

        //return $triage->getId();
    }
}
